version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/api-platform/express
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/api-platform/next12
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/api-platform/next13
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/connect
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/crud/next12
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/crud/next13
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/health-check
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/nextra
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/__fixtures__/framework/express
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/__fixtures__/framework/fastify
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/__fixtures__/framework/hapi
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/__fixtures__/framework/koa
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/__fixtures__/framework/next
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/__fixtures__/framework/unknown
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/cli/commander
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/cli
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/next
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/next/pages/redoc
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform/next/pages/swagger
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/api-platform
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/connect
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/crud/next
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/crud
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/health-check
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/jsdoc-open-api/__fixtures__
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/jsdoc-open-api/cli/commander
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/jsdoc-open-api/cli
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/jsdoc-open-api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/nextra-theme-docs
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/pagination
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/prisma-dmmf-transformer
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/readdir
    schedule:
      interval: daily
