version: "3.7"

services:
    db:
        image: "postgres:15.1-alpine"
        volumes:
            - "${PWD}/data:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: "visulima"
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "visulima"
        ports:
            - "5432:5432"

    redis:
        image: "redis:7.0.7-alpine"
        ports:
            - "6379:6379"

    mailhog:
        image: "mailhog/mailhog:v1.0.1"
        ports:
            - "1025:1025"
            - "8025:8025"
        volumes:
            - "${PWD}/data:/data"
        depends_on:
            - "db"

    localstack:
        image: "localstack/localstack:1.3"
        environment:
            - "AWS_DEFAULT_REGION=us-east-1"
            - "EDGE_PORT=4566"
            - "SERVICES=lambda,s3"
        ports:
            - "4566-4583:4566-4583"
        volumes:
            - "${PWD}/data:/var/lib/localstack/state"
            - '/var/run/docker.sock:/var/run/docker.sock'

    gcs:
        image: "fsouza/fake-gcs-server:1.39.0"
        ports:
            - "4443:4443"
        volumes:
            - "${PWD}/data:/data"

    azure:
        image: "mcr.microsoft.com/azure-storage/azurite:latest"
        ports:
            - "10000:10000" # blob
            - "10001:10001" # queue
            - "10002:10002" # table
        volumes:
            - "${PWD}/data:/data"

volumes:
    data: # yamllint disable-line rule:empty-values
