version: "3.7"

services:
    db:
        image: "postgres:15.1-alpine"
        volumes:
            - "./data/postgresql:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: "visulima"
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "visulima"
            PGDATA: "/var/lib/postgresql/data"
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "ckan" ]
        ports:
            - "5433:5432"

    redis:
        image: "redis:7.0.7-alpine"
        ports:
            - "6379:6379"

    mailhog:
        image: "mailhog/mailhog:v1.0.1"
        ports:
            - "1025:1025"
            - "8025:8025"
        volumes:
            - "./data/mailhog:/data"
        depends_on:
            - "db"

    localstack:
        image: "localstack/localstack:1.3"
        environment:
            - "AWS_DEFAULT_REGION=us-east-1"
            - "EDGE_PORT=4566"
            - "SERVICES=lambda,s3"
            - "PERSISTANCE=1"
        ports:
            - "4566-4583:4566-4583"
        volumes:
            - "./data/localstack:/var/lib/localstack/state"
            - '/var/run/docker.sock:/var/run/docker.sock'

    gcs:
        image: "fsouza/fake-gcs-server:1.43.0"
        ports:
            - "4443:4443"
        command: ["-scheme", "http", "-port", "4443"]
        volumes:
            - "./data/fake-gcs:/data"

    azure:
        image: "mcr.microsoft.com/azure-storage/azurite:latest"
        ports:
            - "10000:10000" # blob
            - "10001:10001" # queue
            - "10002:10002" # table
        volumes:
            - "./data/azure:/data"

volumes:
    data: # yamllint disable-line rule:empty-values
