version: "3.7"

services:
    db:
        image: "postgres:16.1-alpine@sha256:884718395ee967fc70374563f3b4d72f0c61f48f81868decb9fa452915fe070e"
        volumes:
            - "data:/var/lib/postgresql/data"
        ports:
            - "5432:5432"

    redis:
        image: "redis:7.2.4-alpine@sha256:1b503bb77079ba644371969e06e1a6a1670bb34c2251107c0fc3a21ef9fdaeca"
        ports:
            - "6379:6379"

    mailhog:
        image: "mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea"
        ports:
            - "1025:1025"
            - "8025:8025"
        volumes:
            - "data:/data"
        env_file: "./visulima/.env.local"
        depends_on:
            - "db"
        restart: "always"

volumes:
    data: # yamllint disable-line rule:empty-values
