packages:
    - "examples/**"
    - "examples/upload/**"
    - "packages/**"
    - "!**/__fixture__/**"
    - "!**/__fixtures__/**"
    - "!**/__tests__/**"
    - "!**/__test__/**"
    - "visulima"
    - "docs"
