# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Lint"

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - "main"
    pull_request: # yamllint disable-line rule:empty-values

concurrency:
    group: "ci-lint-${{ github.ref }}-1"
    cancel-in-progress: true

permissions:
    contents: "read" # to fetch code (actions/checkout)

jobs:
    eslint:
        name: "Lint (eslint)"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969" # v2.4.0
              with:
                egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab" # v3.5.2
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd" # v2.2.4
              with:
                  version: 8
                  run_install: false

            - name: "Use Node.js 16.x"
              uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c" # v3.6.0
              with:
                  node-version: "16.x"
                  cache: "pnpm"

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"

            - name: "Verify the integrity of provenance attestations and registry signatures for installed dependencies"
              run: "npm audit signatures"

            - name: "Build"
              run: "pnpm run build:packages"

            - name: "lint"
              run: "pnpm run lint:eslint"

    yaml-lint:
        name: "Lint (yaml)"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969" # v2.4.0
              with:
                egress-policy: audit

            - name: "Git checkout"
              uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab" # v3.5.2
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Lint YAML files"
              uses: "ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c" # v3.1.1
              with:
                  config_file: ".yamllint.yaml"
                  file_or_dir: "."
                  strict: true
