name: "Lock File Maintenance"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 */3 * * *" # At minute 0 past every 3rd hour.
    pull_request:
        branches:
            - "dependabot/**"
    workflow_dispatch: # yamllint disable-line rule:empty-values

permissions:
    contents: "read" # for checkout

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/lock-file-maintenance.yml@main"
        permissions: # yamllint disable-line rule:truthy
            contents: "write" # commit and push
            id-token: "write" # for the checkout
        with:
            target-repo: "visulima/visulima"
